srcdir = '.'
blddir = './build'

def set_options(opt):
  opt.tool_options("compiler_cxx")

def configure(conf):
  conf.check_tool("compiler_cxx")
  conf.check_tool("node_addon")

def build(bld):
  obj = bld.new_task_gen("cxx", "shlib", "node_addon") 
  obj.cxxflags = ["-g", "-D_FILE_OFFSET_BITS=64", "-D_LARGEFILE_SOURCE", "-Wall"]
  obj.includes = ["./thunderbird_AB_parser", "../contrib"]
  obj.target = "localcontacts"
  obj.source = "thunderbird_AB_parser/node_contacts_mork.cpp thunderbird_AB_parser/MorkAddressBook.cpp ../contrib/MorkParser.cpp"
