.\" Manpage for webinos.
.TH man 1 "18 Sep 2012" "0.1" "webinos PZP man page"
.SH NAME
WEBINOS \- Webinos framework
.SH SYNOPSIS
webinos_pzp [options]
.SH DESCRIPTION
Webinos_pzp fires up the PZP.
The webinos_pzp command can be launched without parameters or can accept the options.
.SH OPTIONS
.TP
\--help
\ Print a usage message briefly summarizing these command-line options, then exit.
.PP
.TP
\--host=[host] 
\ host of the pzh farm (default localhost)
.TP
\--farm-name=[identifier] 
\ farm name (default machine-name)
.SH SEE ALSO
.SH BUGS
No known bugs.
.SH AUTHOR
Webinos Project https://developer.webinos.org
